Report Grid: person view should included non-direct apps
finos/waltz pull request #6692
Opened 2023-08-04 08:37 UTC by judofosu

2023-08-04 08:50 UTC, judofosu commented
https://github.com/finos/waltz/issues/6602

2023-08-04 13:25 UTC, davidwatkins73 requested changes

2023-08-04 16:32 UTC, davidwatkins73 requested changes
I think swapping this back to `idSelectionOptions` will make the `opts` variable on line 113 redundant.  I think you should be able to safely remove it.  

Also you may want to check to see if the utility method `modifySelectionOptionsForGrid` is used elsewhere.  That may indicate that a similar fix is needed elsewhere.

2023-08-07 10:43 UTC, davidwatkins73 commented
Thanks incorporating the suggestions into the PR.  Merging it now

2023-08-07 10:43 UTC, davidwatkins73 approved these changes

2023-08-07 10:43 UTC, merged